# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XT5.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow5(object):
    def setupUi(self, MainWindow5):
        MainWindow5.setObjectName("MainWindow5")
        MainWindow5.resize(800, 521)
        MainWindow5.setStyleSheet("#centralwidget{\n"
"border-image: url(:/新前缀/img/bg.jpg);\n"
"}\n"
"QLabel{\n"
"color:#ffffff;\n"
"}\n"
"\n"
"QPushButton{\n"
"padding:2px 2px 2px 2px;\n"
"background-color: rgba(255,255,255,100);\n"
"border-style:none;\n"
"border-radius: 5px;\n"
"color:#ffffff;\n"
"}\n"
"QPushButton:hover{\n"
"padding:2px 2px 2px 2px;\n"
"background-color: rgba(220, 220, 220,200);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton:pressed {\n"
"    padding:2px 2px 2px 2px;\n"
"    /* 改变背景色 */  \n"
"    background-color:rgba(180, 180, 180,100);  \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
"    /* 使文字有一点移动 */\n"
"    padding-left:1px;\n"
"    padding-top:1px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#widget_A,#widget_B,#widget_E,#widget_F{\n"
"border-radius:20px;\n"
"    background-color: rgba(255, 255, 255,20);\n"
"}\n"
"#widget_A_1,#widget_B_1,#widget_C_1,#widget_D_1,#widget_E_1,#widget_F_1,#widget_G_1,#widget_H_1{\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"background-color: rgba(20, 36, 48,150);\n"
"}\n"
"\n"
"QTextBrowser{\n"
"padding:2px 2px 2px 2px;\n"
"border-radius:5px;\n"
"    background-color: rgba(255, 255, 255,200);\n"
"}\n"
"\n"
"QTreeWidget{\n"
"padding:2px 2px 2px 2px;\n"
"border-radius:5px;\n"
"background-color: rgba(255, 255, 255,200);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow5)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_C = QtWidgets.QWidget(self.centralwidget)
        self.widget_C.setObjectName("widget_C")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_C)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_C_1 = QtWidgets.QWidget(self.widget_C)
        self.widget_C_1.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_C_1.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_C_1.setObjectName("widget_C_1")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_C_1)
        self.horizontalLayout_12.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_13 = QtWidgets.QLabel(self.widget_C_1)
        self.label_13.setMinimumSize(QtCore.QSize(100, 0))
        self.label_13.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13, 0, QtCore.Qt.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.verticalLayout_8.addWidget(self.widget_C_1)
        self.treeWidget = QtWidgets.QTreeWidget(self.widget_C)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout_8.addWidget(self.treeWidget)
        self.horizontalLayout.addWidget(self.widget_C)
        self.widget_D = QtWidgets.QWidget(self.centralwidget)
        self.widget_D.setObjectName("widget_D")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_D)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_D_1 = QtWidgets.QWidget(self.widget_D)
        self.widget_D_1.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_D_1.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_D_1.setObjectName("widget_D_1")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_D_1)
        self.horizontalLayout_13.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.widget_D_1)
        self.label_14.setMinimumSize(QtCore.QSize(100, 0))
        self.label_14.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14, 0, QtCore.Qt.AlignLeft)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.verticalLayout_9.addWidget(self.widget_D_1)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget_D)
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_9.addWidget(self.textBrowser)
        self.widget = QtWidgets.QWidget(self.widget_D)
        self.widget.setMinimumSize(QtCore.QSize(0, 100))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.PBzstj = QtWidgets.QPushButton(self.widget)
        self.PBzstj.setMinimumSize(QtCore.QSize(80, 25))
        self.PBzstj.setMaximumSize(QtCore.QSize(70, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PBzstj.setFont(font)
        self.PBzstj.setObjectName("PBzstj")
        self.gridLayout.addWidget(self.PBzstj, 1, 0, 1, 1)
        self.PBzssc = QtWidgets.QPushButton(self.widget)
        self.PBzssc.setMinimumSize(QtCore.QSize(80, 25))
        self.PBzssc.setMaximumSize(QtCore.QSize(70, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PBzssc.setFont(font)
        self.PBzssc.setObjectName("PBzssc")
        self.gridLayout.addWidget(self.PBzssc, 2, 0, 1, 1)
        self.PBzstc = QtWidgets.QPushButton(self.widget)
        self.PBzstc.setMinimumSize(QtCore.QSize(80, 25))
        self.PBzstc.setMaximumSize(QtCore.QSize(70, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PBzstc.setFont(font)
        self.PBzstc.setObjectName("PBzstc")
        self.gridLayout.addWidget(self.PBzstc, 2, 1, 1, 1)
        self.PBzsxg = QtWidgets.QPushButton(self.widget)
        self.PBzsxg.setMinimumSize(QtCore.QSize(80, 25))
        self.PBzsxg.setMaximumSize(QtCore.QSize(70, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PBzsxg.setFont(font)
        self.PBzsxg.setObjectName("PBzsxg")
        self.gridLayout.addWidget(self.PBzsxg, 1, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.widget)
        self.horizontalLayout.addWidget(self.widget_D)
        MainWindow5.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow5)

    def retranslateUi(self, MainWindow5):
        _translate = QtCore.QCoreApplication.translate
        MainWindow5.setWindowTitle(_translate("MainWindow5", "MainWindow"))
        self.label_13.setText(_translate("MainWindow5", "知识树"))
        self.label_14.setText(_translate("MainWindow5", "故障说明"))
        self.textBrowser.setHtml(_translate("MainWindow5", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.PBzstj.setText(_translate("MainWindow5", "添加"))
        self.PBzssc.setText(_translate("MainWindow5", "删除"))
        self.PBzstc.setText(_translate("MainWindow5", "退出"))
        self.PBzsxg.setText(_translate("MainWindow5", "修改"))
import img_rc
