# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XT6.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow6(object):
    def setupUi(self, MainWindow6):
        MainWindow6.setObjectName("MainWindow6")
        MainWindow6.resize(689, 491)
        MainWindow6.setStyleSheet("#centralwidget{\n"
"border-image: url(:/新前缀/img/bg.jpg);\n"
"}\n"
"QLabel{\n"
"color:#ffffff;\n"
"}\n"
"QPushButton{\n"
"padding:2px 2px 2px 2px;\n"
"background-color: rgba(255,255,255,100);\n"
"border-style:none;\n"
"border-radius: 5px;\n"
"color:#ffffff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"padding:2px 2px 2px 2px;\n"
"background-color: rgba(220, 220, 220,200);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    padding:2px 2px 2px 2px;\n"
"    /* 改变背景色 */  \n"
"    background-color:rgba(180, 180, 180,100);  \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
"    /* 使文字有一点移动 */\n"
"    padding-left:1px;\n"
"    padding-top:1px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgba(255, 255, 255,120);\n"
"border: 1px solid #000000;\n"
"border-radius:3px;\n"
"color:#ffffff;\n"
"padding-left: 5px;\n"
"}\n"
"QLineEdit:hover\n"
"{\n"
"    border:1px solid rgba(31,156,220) ;\n"
"}\n"
"\n"
"QTextEdit{\n"
"padding:2px 2px 2px 2px;\n"
"background-color: rgba(255, 255, 255,120);\n"
"border: 1px solid #000000;\n"
"border-radius:3px;\n"
"color:#ffffff;\n"
"}\n"
"QTextEdit:hover\n"
"{\n"
"    border:1px solid rgba(31,156,220) ;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow6)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.LE61 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE61.sizePolicy().hasHeightForWidth())
        self.LE61.setSizePolicy(sizePolicy)
        self.LE61.setMinimumSize(QtCore.QSize(0, 25))
        self.LE61.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LE61.setFont(font)
        self.LE61.setObjectName("LE61")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LE61)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.TE61 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TE61.setFont(font)
        self.TE61.setObjectName("TE61")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.TE61)
        self.TE62 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TE62.setFont(font)
        self.TE62.setObjectName("TE62")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.TE62)
        self.LE62 = QtWidgets.QLineEdit(self.centralwidget)
        self.LE62.setMinimumSize(QtCore.QSize(0, 25))
        self.LE62.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LE62.setFont(font)
        self.LE62.setObjectName("LE62")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LE62)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.TE63 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TE63.setFont(font)
        self.TE63.setObjectName("TE63")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.TE63)
        self.verticalLayout.addLayout(self.formLayout)
        self.lb6tip = QtWidgets.QLabel(self.centralwidget)
        self.lb6tip.setText("")
        self.lb6tip.setObjectName("lb6tip")
        self.verticalLayout.addWidget(self.lb6tip)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PB6qd = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB6qd.sizePolicy().hasHeightForWidth())
        self.PB6qd.setSizePolicy(sizePolicy)
        self.PB6qd.setMinimumSize(QtCore.QSize(80, 25))
        self.PB6qd.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PB6qd.setFont(font)
        self.PB6qd.setObjectName("PB6qd")
        self.horizontalLayout.addWidget(self.PB6qd)
        self.PB6qx = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB6qx.sizePolicy().hasHeightForWidth())
        self.PB6qx.setSizePolicy(sizePolicy)
        self.PB6qx.setMinimumSize(QtCore.QSize(80, 25))
        self.PB6qx.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PB6qx.setFont(font)
        self.PB6qx.setObjectName("PB6qx")
        self.horizontalLayout.addWidget(self.PB6qx)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow6.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow6)
        self.PB6qx.clicked.connect(MainWindow6.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow6)

    def retranslateUi(self, MainWindow6):
        _translate = QtCore.QCoreApplication.translate
        MainWindow6.setWindowTitle(_translate("MainWindow6", "MainWindow"))
        self.label.setText(_translate("MainWindow6", "日    期:"))
        self.label_2.setText(_translate("MainWindow6", "故障现象:"))
        self.label_3.setText(_translate("MainWindow6", "故障原因:"))
        self.label_4.setText(_translate("MainWindow6", "负 责 人:"))
        self.label_5.setText(_translate("MainWindow6", "维修方法:"))
        self.PB6qd.setText(_translate("MainWindow6", "确定"))
        self.PB6qx.setText(_translate("MainWindow6", "取消"))
import img_rc
