# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XT7.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow7(object):
    def setupUi(self, MainWindow7):
        MainWindow7.setObjectName("MainWindow7")
        MainWindow7.resize(651, 490)
        MainWindow7.setStyleSheet("#centralwidget{\n"
"border-image: url(:/新前缀/img/bg.jpg);\n"
"}\n"
"\n"
"QPushButton{\n"
"padding:2px 2px 2px 2px;\n"
"background-color: rgba(255,255,255,100);\n"
"border-style:none;\n"
"border-radius: 5px;\n"
"color:#ffffff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"padding:2px 2px 2px 2px;\n"
"background-color: rgba(220, 220, 220,200);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    padding:2px 2px 2px 2px;\n"
"    /* 改变背景色 */  \n"
"    background-color:rgba(180, 180, 180,100);  \n"
"    /* 改变边框风格 */  \n"
"    border-style:inset;  \n"
"    /* 使文字有一点移动 */\n"
"    padding-left:1px;\n"
"    padding-top:1px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgba(255, 255, 255,120);\n"
"border: 1px solid #000000;\n"
"border-radius:3px;\n"
"color:#ffffff;\n"
"padding-left: 5px;\n"
"}\n"
"QLineEdit:hover\n"
"{\n"
"    border:1px solid rgba(31,156,220) ;\n"
"}\n"
"QTableWidget{\n"
"    background-color:rgba(180, 180, 180,200); \n"
"color:#ffffff;\n"
"}\n"
"QHeaderView{\n"
"    background-color:rgba(180, 180, 180,200);      \n"
"}\n"
"\n"
"QHeaderView::section{\n"
"border:none;\n"
"border-right:1px solid rgba(0,0,0,100);\n"
"background-color:rgba(180, 180, 180,200);  \n"
"color:#ffffff;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow7)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LE71 = QtWidgets.QLineEdit(self.centralwidget)
        self.LE71.setMinimumSize(QtCore.QSize(0, 25))
        self.LE71.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LE71.setFont(font)
        self.LE71.setObjectName("LE71")
        self.horizontalLayout.addWidget(self.LE71)
        self.PB7ss = QtWidgets.QPushButton(self.centralwidget)
        self.PB7ss.setMinimumSize(QtCore.QSize(80, 25))
        self.PB7ss.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PB7ss.setFont(font)
        self.PB7ss.setObjectName("PB7ss")
        self.horizontalLayout.addWidget(self.PB7ss)
        self.PB7tc = QtWidgets.QPushButton(self.centralwidget)
        self.PB7tc.setMinimumSize(QtCore.QSize(80, 25))
        self.PB7tc.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PB7tc.setFont(font)
        self.PB7tc.setObjectName("PB7tc")
        self.horizontalLayout.addWidget(self.PB7tc)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tableWidget)
        MainWindow7.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow7)
        QtCore.QMetaObject.connectSlotsByName(MainWindow7)

    def retranslateUi(self, MainWindow7):
        _translate = QtCore.QCoreApplication.translate
        MainWindow7.setWindowTitle(_translate("MainWindow7", "MainWindow"))
        self.PB7ss.setText(_translate("MainWindow7", "搜索"))
        self.PB7tc.setText(_translate("MainWindow7", "退出"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow7", "日期"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow7", "新建列"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow7", "故障原因"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow7", "新建列"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow7", "负责人"))
import img_rc
